### ISSUE TITLE
h5py error in wien2k conversion

### ISSUE THREAD

**Issue by pseth** [TRIQS/dft_tools#42]
Hello,

I am getting the following error for conversion from wien2k, in particular when converting band input. I have not seen this before, and was wondering if anyone else has had it before.

I realise that I am not giving much debug info here -- my main purpose is to find out if this is a common error others have seen (perhaps as a result of recent changes?) or if it points to a mistake in my dmftproj.

Thanks,
Pri

```
[8x64pcweiss mydft] pytriqs converter.py
Starting on 1 Nodes at : 2015-08-23 15:56:04.513676
Reading input from mydft.ctqmcout...
Reading input from mydft.symqmc...
Reading input from mydft.oubwin...
Reading input from mydft.struct...
Reading input from mydft.outputs...
Reading input from mydft.parproj...
Reading input from mydft.sympar...
Reading input from mydft.outband...
Traceback (most recent call last):
  File "converter.py", line 11, in <module>
    Converter.convert_bands_input()
  File "/home/pseth/SOURCES/TRIQS/install/lib/python2.7/site-packages/pytriqs/applications/dft/converters/wien2k_converter.py", line 428, in convert_bands_input
    for it in things_to_save: ar[self.bands_subgrp][it] = locals()[it]
  File "/home/pseth/SOURCES/TRIQS/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 200, in __setitem__
    self._write_array( key, numpy.array(val,copy=1,order='C') )
  File "/home/pseth/SOURCES/TRIQS/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive_basic_layer_h5py.py", line 102, in _write_array
    self._group[key] = numpy.array(val,copy=1,order='C')
  File "build/bdist.linux-x86_64/egg/h5py/_hl/group.py", line 244, in __setitem__
  File "build/bdist.linux-x86_64/egg/h5py/_hl/group.py", line 71, in create_dataset
  File "build/bdist.linux-x86_64/egg/h5py/_hl/dataset.py", line 88, in make_new_dset
  File "h5s.pyx", line 100, in h5py.h5s.create_simple (h5py/h5s.c:1317)
ValueError: zero sized dimension for non-unlimited dimension (Invalid arguments to routine: Bad value)
```

**Comment by parcollet** [comment]
It seems your array has one dim =0, which is not normal.
Print it/its shape by adding a print in the installed df_archive, line 200.

**Comment by pseth** [comment]
Indeed one of the dimensions (n_parproj) is 0, but I am uncertain if this does occur in certain situations for dmftproj.. I will rerun dmftproj.
