### ISSUE TITLE
SK = SumkDFT(hdf_file=dft_filename+'.h5',use_dft_blocks=use_blocks)-bug

### ISSUE THREAD

**Issue by Kristanovski** [TRIQS/dft_tools#70]
Hi
i'm trying to do some spin-polarized LDA+DMFT - calculation for hcp -Cobalt and i have this error:
Traceback (most recent call last):
  File "lda_dmft_cthyb.py", line 48, in <module>
    SK = SumkDFT(hdf_file=dft_filename+'.h5',use_dft_blocks=use_blocks)
  File "/afs/physnet.uni-hamburg.de/software/softsrv/th1li/TRIQS/master@2016.06.09/lib/python2.7/site-packages/pytriqs/applications/dft/sumk_dft.py", line 146, in **init**
    self.analyse_block_structure()
  File "/afs/physnet.uni-hamburg.de/software/softsrv/th1li/TRIQS/master@2016.06.09/lib/python2.7/site-packages/pytriqs/applications/dft/sumk_dft.py", line 741, in analyse_block_structure
    dm = self.density_matrix(method='using_point_integration')
  File "/afs/physnet.uni-hamburg.de/software/softsrv/th1li/TRIQS/master@2016.06.09/lib/python2.7/site-packages/pytriqs/applications/dft/sumk_dft.py", line 886, in density_matrix
    MMat[isp][inu, inu] = 0.0
IndexError: index 21 is out of bounds for axis 0 with size 21

Anyone could help me to solve this problem? Maybe is it just a bug?

**Comment by gkraberger** [comment]
hi, the current version of dft_tools doesn't have the line 

```
 MMat[isp][inu, inu] = 0.0
```
in line 886.

could you check if this is the bug i fixed in 03ea26ec6f53a35e3c1bddcf9c0b5e464e4cc160 ?

**Comment by Kristanovski** [comment]
Yes, ofc. Sorry for the late response
