### ISSUE TITLE
run case SrVO3 by triqs code

### ISSUE THREAD

**Issue by ghragoozloo** [TRIQS/dft_tools#81]
Hi all
Hi all
I am getting a error message when running the following code in a pytriqs SrVO3:
SrVO3.indmftpr
3                ! Nsort
1 1 3            ! Mult(Nsort)
3                ! lmax
complex          ! choice of angular harmonics
1 0 0 0          ! l included for each sort
0 0 0 0          ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
cubic            ! choice of angular harmonics
1 1 2 0          ! l included for each sort
0 0 2 0          ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
01               !
0                ! SO flag
complex          ! choice of angular harmonics
1 1 0 0          ! l included for each sort
0 0 0 0          ! If split into ireps, gives number of ireps. for a given orbital (otherwise 0)
-0.08 0.14       ! t2g + eg + Op

and SrVO3.py:
from pytriqs.applications.dft.sumk_dft import *
from pytriqs.applications.dft.converters.wien2k_converter import *
from pytriqs.applications.impurity_solvers.hubbard_I.hubbard_solver import Solver

import os
dft_filename = 'SrVO3'

beta = 40
U_int = 4.0
J_hund = 0.65
Loops = 3                       # Number of DMFT sc-loops
mixing = 0.7                     # Mixing factor
DC_type = 1                      # 0...FLL, 1...Held, 2... AMF, 3...Lichtenstein
chemical_potential_init=0.0      # initial chemical potential

# Convert DMFT input:
Converter = Wien2kConverter(filename=dft_filename)
Converter.convert_dft_input()
mpi.barrier()

#check if there are previous runs:
previous_runs = 0
previous_present = False
if mpi.is_master_node():
    f = HDFArchive(dft_filename+'.h5','a')
    if 'dmft_output' in f:
        ar = f['dmft_output']
        if 'iterations' in ar:
            previous_present = True
            previous_runs = ar['iterations']
    else:
        f.create_group('dmft_output')
    del f
previous_runs    = mpi.bcast(previous_runs)
previous_present = mpi.bcast(previous_present)

# Init the SumK class
SK=SumkDFT(hdf_file=dft_filename+'.h5',use_dft_blocks=False)

Norb = SK.corr_shells[0]['dim']
l    = SK.corr_shells[0]['l']

# Init the Hubbard-I solver:
S = Solver(beta = beta, l = l)

chemical_potential=chemical_potential_init
# load previous data: old self-energy, chemical potential, DC correction
if previous_present:
    if mpi.is_master_node():
        ar = HDFArchive(dft_filename+'.h5','a')
        S.Sigma << ar['dmft_output']['Sigma']
        del ar
        SK.chemical_potential,SK.dc_imp,SK.dc_energ = SK.load(['chemical_potential','dc_imp','dc_energ'])
    S.Sigma << mpi.bcast(S.Sigma)
    SK.chemical_potential = mpi.bcast(SK.chemical_potential)
    SK.dc_imp = mpi.bcast(SK.dc_imp)
    SK.dc_energ = mpi.bcast(SK.dc_energ)

# DMFT loop:
for iteration_number in range(1,Loops+1):
    
        itn = iteration_number + previous_runs
       
        # put Sigma into the SumK class:
        SK.set_Sigma([ S.Sigma ])

        # Compute the SumK, possibly fixing mu by dichotomy
        chemical_potential = SK.calc_mu( precision = 0.000001 )
                  
        # Density:
        S.G <<= SK.extract_G_loc()[0]
        mpi.report("Total charge of Gloc : %.6f"%S.G.total_density())

        # calculated DC at the first run to have reasonable initial non-interacting atomic level positions
        if ((iteration_number==1)and(previous_present==False)):
            dc_value_init=U_int/2.0
            dm=S.G.density()
	    SK.calc_dc( dm, U_interact = U_int, J_hund = J_hund, orb = 0, use_dc_formula = DC_type, use_dc_value=dc_value_init)

        # calculate non-interacting atomic level positions:
        eal = SK.eff_atomic_levels()[0]
        S.set_atomic_levels( eal = eal )

        # solve it:
        S.solve(U_int = U_int, J_hund = J_hund, verbosity = 1)

        # Now mix Sigma and G with factor Mix, if wanted:
        if (iteration_number>1 or previous_present):
            if (mpi.is_master_node() and (mixing<1.0)):
                ar = HDFArchive(dft_filename+'.h5','a')
                mpi.report("Mixing Sigma and G with factor %s"%mixing)
                S.Sigma << mixing * S.Sigma + (1.0-mixing) * ar['dmft_output']['Sigma']
                S.G << mixing * S.G + (1.0-mixing) * ar['dmft_output']['G']
                del ar
            S.G << mpi.bcast(S.G)
            S.Sigma << mpi.bcast(S.Sigma)
     
        
        # after the Solver has finished, set new double counting: 
        dm = S.G.density()
        SK.calc_dc( dm, U_interact = U_int, J_hund = J_hund, orb = 0, use_dc_formula = DC_type )

        # correlation energy calculations:
        SK.correnerg = 0.5 * (S.G * S.Sigma).total_density()
        mpi.report("Corr. energy = %s"%SK.correnerg)

        # store the impurity self-energy, GF as well as correlation energy in h5
        if mpi.is_master_node():
            ar = HDFArchive(dft_filename+'.h5','a')
            ar['dmft_output']['iterations'] = iteration_number + previous_runs
            ar['dmft_output']['G'] = S.G
            ar['dmft_output']['Sigma'] = S.Sigma
            del ar

        #Save essential SumkDFT data:
        SK.save(['chemical_potential','dc_imp','dc_energ','correnerg'])
        if (mpi.is_master_node()):
            print 'DC after solver: ',SK.dc_imp[0]

        # print out occupancy matrix of Ce 4f
        mpi.report("Orbital densities of impurity Green function:")
        for s in dm:
            mpi.report("Block %s: "%s)
            for ii in range(len(dm[s])):
                str = ''
                for jj in range(len(dm[s])):
                    if (dm[s][ii,jj].real>0):
                        str += "   %.4f"%(dm[s][ii,jj].real)
                    else:
                        str += "  %.4f"%(dm[s][ii,jj].real)
                mpi.report(str)
        mpi.report("Total charge of impurity problem : %.6f"%S.G.total_density())

# find exact chemical potential
SK.chemical_potential = SK.calc_mu( precision = 0.000001 )

# calculate and save occupancy matrix in the Bloch basis for Wien2k charge denity recalculation
dN,d = SK.calc_density_correction(filename = dft_filename+'.qdmft')

mpi.report("Trace of Density Matrix: %s"%d)

# store correlation energy contribution to be read by Wien2ki and then included to DFT+DMFT total energy
if (mpi.is_master_node()):
    SK.correnerg -= SK.dc_energ[0]
    f=open(dft_filename+'.qdmft','a')
    f.write("%.16f\n"%SK.correner(.my_python) [hadi@localhost SrVO3]$ pytriqs SrVO3.py
Starting on 1 Nodes at : 2017-11-02 12:26:27.002215
Reading input from SrVO3.ctqmcout...
Reading input from SrVO3.symqmc...
Reading input from SrVO3.oubwin...
Reading input from SrVO3.struct...
Reading input from SrVO3.outputs...
Dichotomy adjustment of Chemical Potential to obtain Total Density = 1.000000 +/- 0.000001
    Chemical Potential = -0.500000  
    Total Density = 0.391618
    0.000000 < Chemical Potential < -0.500000
    1.003153 < Total Density < 0.391618
    -0.002578 < Chemical Potential < -0.500000
    1.001664 < Total Density < 0.391618
    -0.003935 < Chemical Potential < -0.500000
    1.000890 < Total Density < 0.391618
    -0.004660 < Chemical Potential < -0.500000
    1.000479 < Total Density < 0.391618
    -0.005050 < Chemical Potential < -0.500000
    1.000259 < Total Density < 0.391618
    -0.005261 < Chemical Potential < -0.500000
    1.000140 < Total Density < 0.391618
    -0.005375 < Chemical Potential < -0.500000
    1.000076 < Total Density < 0.391618
    -0.005436 < Chemical Potential < -0.500000
    1.000041 < Total Density < 0.391618
    -0.005470 < Chemical Potential < -0.500000
    1.000022 < Total Density < 0.391618
    -0.005488 < Chemical Potential < -0.500000
    1.000012 < Total Density < 0.391618
    -0.005498 < Chemical Potential < -0.500000
    1.000006 < Total Density < 0.391618
    -0.005503 < Chemical Potential < -0.500000
    1.000003 < Total Density < 0.391618
    -0.005506 < Chemical Potential < -0.500000
    1.000002 < Total Density < 0.391618
    -0.005508 < Chemical Potential < -0.500000
    1.000001 < Total Density < 0.391618
    -0.005509 < Chemical Potential < -0.500000
    1.000000 < Total Density < 0.391618
    Chemical Potential found in 15 iterations : 
    Total Density = 1.000000;Chemical Potential = -0.005509
Traceback (most recent call last):
  File "SrVO3.py", line 71, in <module>
    S.G <<= SK.extract_G_loc()[0]
  File "/home/hadi/triqs2/install/lib/python2.7/site-packages/pytriqs/gf/local/block_gf.py", line 257, in __ilshift__
    for (i,g) in self: g.copy_from(A[i])
RuntimeError: .. Error occurred at Thu Nov  2 12:26:57 2017

.. Error .. calling C++ overload 
.. copy_from(gf_view<imfreq,matrix_valued,tail> other) -> void 
.. in implementation of method GfImFreq.copy_from
.. C++ error was : 
.. Triqs runtime error at /home/hadi/triqs2/triqs.src/triqs/./gfs/./impl/../singularity/tail.hpp : 306

tails are incompatible
.. Error occurred on node 0

(.my_python) [hadi@localhost SrVO3]$ 

    f.close()
error:

**Comment by aichhorn** [comment]
Sorry, this is exactly the same problem that you already posted in issue #495 in the triqs issues list. You are again using Hubbard I, but try to set up Wanniers only for t2g. That will never work.

**Comment by ghragoozloo** [comment]
Thanks all 
I studied and tried on your suggestions ...but the result isn't perfect as I expected.
Plz help me to overcome this issue.

**Comment by ghragoozloo** [comment]
Quoting Markus Aichhorn <notifications@github.com>:

> Sorry, this is exactly the same problem that you already posted in  
> issue #495 in the triqs issues list. You are again using Hubbard I,  
> but try to set up Wanniers only for t2g. That will never work.
>
>   —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub[1], or mute the thread[2].
>       



Links:
------
[1] https://github.com/TRIQS/dft_tools/issues/81#issuecomment-341367156
[2]
