### ISSUE TITLE
SrVO3 example does not work anymore with TRIQS 2.0 master

### ISSUE THREAD

**Issue by asubedi** [TRIQS/dft_tools#98]
The SrVO3 example is no longer working with TRIQS master because of the following error:

Traceback (most recent call last):
  File "SrVO3-el1.py", line 110, in <module>
    ar['dmft_output']['Delta_iw'] = delta(S.G0_iw)
  File "/home/subedi/softwares/TRIQS-2.0-git/install/lib/python2.7/site-packages/pytriqs/gf/tools.py", line 72, in delta
    raise RuntimeError, "OBSOLETE : TO BE REPLACED"
RuntimeError: OBSOLETE : TO BE REPLACED

**Comment by mzingl** [comment]
@parcollet : Why is the the delta function obsolete in pytriqs/gf/tools.py ?
For this DFTTools example it is not important we can store G0 instead, but I think Hugo might also want to use the function for the cthyb solver. I would say it is useful.

**Comment by asubedi** [comment]
I just talked to @mferrero, and he does not know why delta() was obsoleted. 

I could run the script by commenting out the exception, but I guess there must be a reason why that function was obsoleted.

Without that function, the example and DFT+DMFT calculations cannot be performed. 

Can anyone tell me if it is safe to comment out the exception and proceed to do the calculations?

Best,
Alaska

**Comment by mzingl** [comment]
Well, you don't need it for the DMFT calculation. The hybridization is extracted by the cthyb solver.
In the example the lines with delta are only there for the mixing, which is often not necessary. You can just uncomment these lines in the example. 

I'll talk to @parcollet about the status of the delta() function. This should be fixed.

Best,
Manuel
